mozilla-extensions/webcompat-addon

src/bootstrap.js
=> Bug 1307792 - Add preference for disabling UA overrides

src/content/data/ua_overrides.js, src/content/lib/ua_overrider.js
Found some issues with docs while investigating `Go Faster` add-ons.. 👀
=> No Bug - Fix up some docs

src/.eslintrc, src/bootstrap.js
As discussed just now.
r? @MDTsai
=> No bug - Fix eslint style issues

src/bootstrap.js, src/content/lib/ua_overrider.jsm
See [bug 1328853](https://bugzilla.mozilla.org/show_bug.cgi?id=1328853).
=> Bug 1328853 - Don't always print the console message

src/test/browser_overrider.js
Change use defineLazyModuleGetter from ua_overrider.js to ua_overrider.jsm
=> Fix mochitest

src/moz.build
r? @miketaylr, see [bug 1337806](https://bugzilla.mozilla.org/show_bug.cgi?id=1337806)
=> Bug 1337806 - Add BUG_COMPONENT

src/content/lib/ua_overrider.jsm
r? @MDTsai, see [bug 1337785](https://bugzilla.mozilla.org/show_bug.cgi?id=1337785)
=> Bug 1337785 - Don't act on URIs where we can't get the baseDomain

src/content/lib/ua_overrider.jsm, src/test/browser_overrider.js
r? @MDTsai, see [bug 1337782](https://bugzilla.mozilla.org/show_bug.cgi?id=1337782)
=> Bug 1337782 - Remove URI caching

src/bootstrap.js, src/content/lib/ua_overrider.jsm
=> Bug 1376573 - Override the UserAgents via UserAgentOverrides.jsm

src/bootstrap.js
=> Bug 1371442 - Initialize UAOverrides after UserAgentsOverride.jsm

src/webextension/background.js, src/webextension/injections/js/bug1457335-histography.io-ua-change.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1457335 and linked bugs for details.
=> Bug 1457335 - Override UA and navigator.vendor for histography.io

src/webextension/background.js, src/webextension/injections/js/bug1472075-bankofamerica.com-ua-change.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1472075 and linked bugs for details.
=> Bug 1472075 - UA override for Bank of America for OSX & Linux

src/webextension/background.js, src/webextension/injections/js/bug1472081-election.gov.np-window.sidebar-shim.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1472081 and linked bugs for details.
=> Bug 1472081 - election.gov.np - Override window.sidebar with something falsey

src/webextension/background.js
This PR enables us to write platform-specific content scripts, as well as universal ones. This is needed to avoid Fennec running overrides that are not designed for Fennec.
=> No bug - Add support for platform-specific content scripts

src/injections.js
See https://mozilla.slack.com/archives/C4FMB0AJY/p1541199855013000
=> No bug - Apply UA override on histography.io for https as well

src/ua_overrides.js
See individual commits for bug numbers.
=> Bug 1505828 - Add further UA overrides

src/ua_overrides.js
=>  Bug 1464106 - Create UA override for directvnow.com

package.json, src/injections.js, src/injections/js/bug1522755-ebay-scroll-anchoring.js, src/manifest.json
~This is a WIP for further discussion. Ignore for now. :)~
See https://bugzilla.mozilla.org/show_bug.cgi?id=1520666 for more details.
=> Bug 1522755 - Override infinity.js method to fix scroll anchoring issues

src/AboutCompat.jsm, src/aboutCompat.css, src/aboutCompat.html, src/aboutCompat.js, src/aboutPage.js, src/injections.js, src/manifest.json, src/ua_overrides.js
Sorry for the delay here. This is a roll-up patch containing the last batch of fixes for about:compat, as well as the PDK5 intervention (this makes us match what's in mozilla-central right now).
=> Roll-up of about:compat QA fixes and the PDK5 intervention. Fixes #43

src/injections.js, src/injections/css/bug1432935-breitbart.com-webkit-scrollbar.css, src/injections/css/bug1432935-discordapp.com-webkit-scorllbar-white-line.css
Only two left! All the other sites fixed themselves after we were strong with outreach. :)
=> Bug 1432935 - Add remaining -webkit-sidebar cases

package.json, src/ua_overrides.js
=> Bug 1545098 - Remove some UA overrides and Interventions + update web-ext version

Jakefile, README.md
After the work is completed and merged, we need to adjust the readme.
(I'm going to merge this myself, as this is just a README change and removing undocumented jake commands, but I wanted to test if the PR tests are working as well.)
=> Bug 1444192 - Follow-up: Documentation for new tests

src/data/ua_overrides.js
=> Bug1563839 - UA override for rolb.santanderbank.com

src/data/ua_overrides.js
=> Bug 1566253 - UA override for posts.google.com

src/data/ua_overrides.js
=> Bug 1567198 - UA override for *.santander.co.uk

src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1567610-dns.google.com-moz-fit-content.css, src/injections/css/bug1568256-zertifikate.commerzbank.de-flex.css
=> Bug 1567945 - override for beeg.com and Bug 1568256 - intervention for zertifikate.commerzbank.de 

src/data/ua_overrides.js
=> Bug 1568636 - UA override for bob.santanderbank.com

src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1570119-teamcoco.com-scrollbar-width.css, src/injections/css/bug1570328-developer-apple.com-transform-scale.css
=> Bug 1570390 - UA override for zhidao.baidu.com, Bug 1570119 - Intervention for teamcoco.com and Bug 1570328 - Intervention for developer.apple.com

src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1571036-mobile.aireuropa.com-menu-fix.css, src/injections/js/bug1570856-medium.com-menu-isTier1.js
=> Bug 1570108 - UA override for steamcommunity.com, Bug 1571036 - intervention and UA override for mobile.aireuropa.com

spec/injections.spec.js, src/data/injections.js, src/data/ua_overrides.js, src/lib/custom_functions.js, src/manifest.json
=> Bug 1582582 - UA override for sling.com

src/manifest.json
Oops, forgot to do this in #88 
r? @denschub
=> Bug 1587558 - Update minor version number

src/data/injections.js, src/injections/css/bug1605611-maps.google.com-directions-time.css, src/injections/js/bug1605611-maps.google.com-directions-time.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1605611#c0 for details.
Fixes https://github.com/webcompat/web-bugs/issues/39281
=> Bug 1605611 - Fix the time picker of Google Maps' transit section

spec/helpers/mock_webextension_apis.js, src/data/ua_overrides.js, src/experiment-apis/systemManufacturer.js, src/experiment-apis/systemManufacturer.json, src/manifest.json, src/moz.build
~~**Do not merge**.~~
~~This works, but needs some more testing. I'll tackle this when I'm back at work after my vacation, but I wanted to dump this code onto GitHub, just in case.~~
Ready for review. r? @ksy36
=> Bug 1598198 - Add User Agent modification for galaxy.store URLs

README.md
=> Adjust documentation with extensions.experiments.enabled pref

spec/intervention_helpers.spec.js, src/data/injections.js, src/data/ua_overrides.js, src/lib/intervention_helpers.js, src/manifest.json, src/moz.build
This is to address [this question](https://bugzilla.mozilla.org/show_bug.cgi?id=1622056#c2), and to provide a nicer solution for a use-case that's not too uncommon.
r? @miketaylr
=> No issue - Turn Google TLD helper into a generalized solution for more cases.

src/data/ua_overrides.js
=> Bug 1622063 - Add UA override for wp1-ext.usps.gov

src/data/injections.js
Creating a draft pull request, because I have a question on how to address Ancestry.com here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1622056#c2
=> Bug 1622056 - Add a few more Salesforce Communities sites

src/data/injections.js, src/injections/js/bug1623375-salesforce-communities-hide-unsupported.js
(this way it's less confusing to test)
r? @ksy36
=> Bug 1623303 - Add a dedicated Salesforce Communities tracking bug

src/data/injections.js, src/lib/custom_functions.js
r? @ksy36 
Tested and working on a custom Fennec build.
(Note: going to file a follow-up bug, because it seems like some of this could be abstracted)
=> Bug 1622062 - Rewrite preventDefault:true for $.detectSwipe

README.md, src/manifest.json
r? @denschub 
(my prettier-vscode installation insisted on formatting the JSON file, seems ok?)
=> Bug 1621062 - Bump version to 9.0.0

src/injections/js/bug1629926-mail.google.com-hangouts-mic-fix.js, src/manifest.json
(this has been merged to mozilla-central)
r? @miketaylr
=> Bug 1632947 - Fix for the gmail intervention causing delay

.gitignore
=> No issue - Ignore web-ext output

src/data/injections.js, src/injections/css/bug1633796-www-la-poste-fr-placeholder-fix.css
r? @ksy36 
(I've tested this locally on Fennec)
=> Bug 1633796 - Add CSS intervention for www.laposte.fr login

src/data/ua_overrides.js
This will give the possibility for the page to load on https://www.jp.square-enix.com/music/sem/page/FF7R/ost/
=> Bug 1651292. Adds UA override to www.jp.square-enix.com

src/data/injections.js, src/injections/css/bug1651917-teletrader.com.body-transform-origin.css
Fix the body transform origin position for teletrader.com
See https://bugzilla.mozilla.org/show_bug.cgi?id=1651917
and https://github.com/webcompat/web-bugs/issues/55217
=> Bug 1651917 - Adds CSS intervention for teletrader.com

src/data/ua_overrides.js
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1652396
=> Bug 1652396 - Remove UA Override for cineflix.com.br

src/data/ua_overrides.js, src/manifest.json
=> Bug 1654524 - Fix santander match pattern

src/manifest.json
=> Bug 1649243 - Bump version to 14.0.0

package-lock.json, package.json
This addresses the security warning in the repo, which have no actual effect, but are annoying. Just a drive-by.
=> No bug - Update devDependencies.

README.md, src/data/ua_overrides.js, src/injections/css/bug1561371-mail.google.com-allow-horizontal-scrolling.css
=> Fixes #178 - Remove references to Fennec in docs and comments

src/data/ua_overrides.js
=> Bug 1665129 - Add *.gruposantander.es to the Santander intervention.

package-lock.json, package.json
Mainly to silence the warning about the vulnerability in `node-forge`. 
r? @ksy36
=> No bug - Update build dependencies.

src/experiment-apis/matchPatterns.json
https://github.com/mozilla-mobile/android-components/issues/7557
I follow exactly the iOS changes on this PR: https://github.com/mozilla-mobile/firefox-ios/pull/6783/files
=> Renaming blacklist/whitelist aligned with android-components #7557

src/data/injections.js, src/injections/js/bug1677442-store.hp.com-disable-indexeddb.js, src/manifest.json
=> Bug 1677442 - Intervention for store.hp.com

src/data/injections.js, src/injections/js/bug1682238-gamearter.com-ua-change.js
=> Bug 1682238 - gamearter.com: Override macOS version number in UA string from 11.0 to 10.16.

src/manifest.json
=> Bug 1682238 - version bump

src/data/ua_overrides.js, src/manifest.json
=> Bug 1686065 - v19.0.0 of webcompat system addon

src/shims/google-analytics.js
Let's take this and make sure it lands on mobile as well.
=> Backport fix for bz1516552

src/about-compat/aboutCompat.css
Last minute update of the CSS.
=> Bug 1698408 - Clean up about:compat desktop CSS and redesign its mobile CSS

src/data/injections.js, src/injections/js/bug1711082-m.aliexpress.com-undisable-search.js
=> Bug 1711082 - Cannot trigger search bar on AliExpress mobile page

src/data/ua_overrides.js
These are the modifications of the webcompat system addon v25.0.0 for Firefox 92.
=> Bug 1720138 - Ship v25.0.0 of webcompat system addon

src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1741234-patient.alphalabs.ca-height-fix.css, src/injections/css/bug1743041-lu.ma-display-fix.css
This is the pull request for Site Interventions v29
=> Interventions for Version 29

.taskcluster.yml
This is blocking #265, see https://github.com/mozilla-extensions/xpi-manifest/pull/152
=> No bug - Update taskgraph revision.

package-lock.json, package.json, src/data/injections.js, src/injections/js/bug1769762-tiktok.com-plugins-shim.js, src/manifest.json
=> Bug 1769762 - Override navigator.plugins for Tiktok

package-lock.json, package.json, src/data/injections.js, src/data/shims.js, src/data/ua_overrides.js, src/injections/js/bug1772949-youtube-webshare-shim.js, src/injections/js/bug1778239-m.pji.co.kr-banner-hide.js, src/lib/custom_functions.js, src/lib/ua_helpers.js, src/manifest.json, src/shims/adnexus-ast.js, src/shims/branch.js, src/shims/everest.js, src/shims/fastclick.js, src/shims/firebase.js, src/shims/google-publisher-tags.js
Bugzilla meta-bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1776673
(Note that the Firebase shim update is a backport, and has already landed on mozilla-central)
=> V104.0.0 interventions, injections and shims

src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1784141-aveeno.com-unsupported.css, src/injections/css/bug1784195-nutmeg.morrisons.com-overflow.css, src/injections/css/bug1784199-entrata-platform-unsupported.css, src/injections/css/bug1784351-movistar.com.ar-overflow-overlay-fix.css, src/injections/css/bug1784546-seznam.cz-popup-height.css
=> Ship v105.0.0 of the WebCompat System Addon

package-lock.json, package.json, src/data/injections.js, src/injections/css/bug1743614-storytel.com-flex-min-width.css, src/injections/css/bug1768243-cloud.google.com-allow-table-scrolling.css, src/manifest.json
Sorry for making this a really small one - I completely dropped the ball on this, and only got reminded of it because today is soft-freeze. I'll make it up next time. :)
=> Bug 1805407 - Interventions for v110

package-lock.json, package.json, src/data/injections.js, src/data/ua_overrides.js, src/injections/css/bug1830813-page.onstove.com-hide-unsupported.css, src/injections/js/bug1855014-eksiseyler.com.js, src/injections/js/bug1855071-www.meteoam.it.js, src/manifest.json, src/moz.build
https://bugzilla.mozilla.org/show_bug.cgi?id=1838840
(Note that the fix for bug 1851929/gbf.game.mbga.jp has already landed, and so is not included in these patches)
=> Bug 1838840 - Patches for version 119.0.0

spec/ua_helpers.spec.js, src/data/ua_overrides.js, src/lib/ua_helpers.js
=> Bug 1858664 - UA override to freeze rv segment to 109

src/data/injections.js, src/injections/css/bug1863420-tv.apple.com-dialog-fix.css
=> Bug 1863420 - Add an intervention for tv.apple.com

src/data/injections.js, src/injections/js/bug1799968-www.samsung.com-appVersion-linux-fix.js
Apply bug 1799968's intervention for samsung.com on Linux to Android.
=> Bug 1860417 - Add intervention for samsung.com on Android

package-lock.json, package.json, src/data/injections.js, src/injections/js/bug1889326-office365-email-handling-prompt-autohide.js, src/manifest.json
=> Bug 1889326 - Re-ship Outlook 365 mailto: handler prompt intervention.

src/data/ua_overrides.js
=> Bug 1904908 - Update intervention for directv.com

Jakefile, README.md, src/manifest.json
Do not merge until https://bugzilla.mozilla.org/show_bug.cgi?id=1943108 stuck.
=> Bug 1943108 - Remove Android logic from export tooling
