mozilla-extensions/webcompat-addon

- src/bootstrap.js
- src/install.rdf.in
- src/jar.mn
- src/webextension/manifest.json
- src/webextension/tablog.js
Embed a WebExtension to receive tab update event.
While tab is loading and the URL matches override rule,
Injects a javascript to print console log.
Uses chrome.runtime.onMessage to link WebExtension and UAOverrider.
> Bug 1307788 - Implement Developer Tools notification

- src/content/data/ua_overrides.js
This is a dummy override that overrides the User Agent on webcompat.com to Chromes UA. This results in the Chrome Add-on being offered instead of the Firefox addon. Obviously, this is nothing we want to leave in place when landing to m-c, but QA needs something to test.
r? @MDTsai
> Add dummy override for webcompat.com

- package.json
- src/install.rdf.in
- src/webextension/background.js
- src/webextension/injections/js/bug1452707-window.controllers-shim-ib.absa.co.za.js
This deprecates #21 as per [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1452707#c5).
r? @wisniewskit for the technical part,
r? @miketaylr as a second reviewer and management approval!
> Bug 1452707 - Shim window.controllers for ib.absa.co.za

- src/content/data/ua_overrides.jsm
See https://bugzilla.mozilla.org/show_bug.cgi?id=755590
This simply appends `Chrome/68.0.3440.85 Mobile Safari/537.36` to the UA for Google Sites, which is enough to have the correct header shown. I did a few tests, and it seems to be working as it should. That being said, Google does not like Sites on mobile devices, and you are unable to edit anything, even on Chrome for Android. All you do is a "Please use Chrome" message - even in Chrome. I guess they want people to use desktop browsers.
> Bug 755590 - Add UA override for sites.google.com

- src/content/data/ua_overrides.jsm
This replaces the User Agent for Imgur on Fenenc to something that looks like
```
Mozilla/5.0 (Android 8.0.0; Mobile; rv:63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.85 Mobile Safari/537.36
```
Sadly, simply appending some identifies was not enough to convince Imgur to provide us the CSS and JS files, so I had to replae everything after the first parenthesis.
> Bug 1480710 - m.imgur.com - Build UA override

- src/webextension/background.js
- src/webextension/injections/js/bug1482066-portalminasnet.com-window.sidebar-shim.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1482066 and https://webcompat.com/issues/18143
The override is identical to the one in #25, but I created a separate file so we do not have to mix comments and inclusion rules, which should make removing an override easier.
> portalminasnet.com - Override window.sidebar with something falsey

- src/ua_overrides.js
This PR includes 9 additional UA Overrides for us to ship.
* 7 of them are simply imports from `ua-update.json.in` so we eventually can remove the old mechanism.
* The mobile.de override is tracked in [bug 969844](https://bugzilla.mozilla.org/show_bug.cgi?id=969844).
* The mobile.bet365.com override is tracked in [bug 1476436](https://bugzilla.mozilla.org/show_bug.cgi?id=1476436).
Testing these in current Fennec nightlies can be hard, as `web-ext` is not supporting them right now, see https://github.com/mozilla/web-ext/pull/1391. However, testing in Beta works just fine, and so does compiling Fennec yourself. When testing the `ua-update.json.in` ports, be sure to toggle `general.useragent.site_specific_overrides` and `general.useragent.updates.enabled` to false to disable the old …
> Add lots of UA Overrides

- Jakefile
- README.md
- package.json
As we are a webextension now, running the extension is simpler. For desktop, `about:debugging` is the way to go, and for mobile, using `web-ext` is simpler than running in a self-built Fennec all the time. This PR adjusts the readme accordingly.
The second commit is just updating the dev dependencies. I figured I could do that if I'm on it anyway. :)
> Documentation adjustments

- src/ua_overrides.js
The UA override is no longer needed, and the Chrome UA is now causing actual WebCompat issues as well, see https://github.com/webcompat/web-bugs/issues/18496. Let's drop this.
> Bug 1487401 - Remove mobile UA override for eBay

- src/injections.js
- src/injections/css/bug1526977-sreedharscce.in-login-fix.css
- src/ua_overrides.js
As discussed, here are two site interventions for us to roll out in our initial test:
* [Bug 1526977](https://bugzilla.mozilla.org/show_bug.cgi?id=1526977) - sreedharscce.in - Fix login form with CSS intervention (see https://github.com/webcompat/web-bugs/issues/21505)
* [Bug 1518625](https://bugzilla.mozilla.org/show_bug.cgi?id=1518625) - Add UA override for rottentomatoes.com
r? @wisniewskit 
cc @adamopenweb
> Add interventions for initial rollout test

- src/injections.js
- src/injections/css/bug1305028-gaming.youtube.com-webkit-scrollbar.css
- src/injections/css/bug1518781-twitch.tv-webkit-scrollbar.css
As a Proof-of-Concept, let's address two cases of broken layouts caused by the use of `::-webkit-scrollbar`. This PR contains interventions for two sites:
* [Bug 1305028](https://bugzilla.mozilla.org/show_bug.cgi?id=1305028): Here, the intervention hides the scrollbar in the main player section only. YouTube is using `::-webkit-scrollbar` to make all scrollbars on the site a fixed width, but as far as I can tell, only the main player area scrollbar is an issue, because it gets partly overlapped by the video player.
* [Bug 1518781](https://bugzilla.mozilla.org/show_bug.cgi?id=1518781): The scrollbar prevents users to click on the three-dot-button to access chat message interactions reliably. As discussed in scrollbar, setting the width to `thin` is not enough, so this intervention removes …
> Multiple bugs - Address two ::-webkit-scrollbar cases

- README.md
> Fix web-ext link's Markdown syntax

- .prettierrc
- README.md
- package.json
`mozilla-central` now follows the prettier style guide and uses that tool to autoformat. Since the sources in this repo end up in m-c as well, it makes sense that we have support for running prettier. The config we have in m-c is really slim, so I feel good with just copying it over.
r? @ksy36
> Add prettier.

- src/about-compat/aboutCompat.js
- src/data/injections.js
- src/data/ua_overrides.js
- src/injections/css/bug0000000-testbed-css-injection.css
- src/injections/js/bug0000000-testbed-js-injection.js
- src/lib/about_compat_broker.js
This re-adds the manual verification testbed as we've discussed yesterday. It points to [the new testbed](https://github.com/mozilla/webcompat-addon-testbed/), which is auto-deployed and can be managed by the entire team, so there no longer is a dependency or a reference to my private infrastructure in there. 🎉 
My commit is complete, but I'd like this PR to contain a second commit that blacklists the test interventions from `about:config`. @wisniewskit, I pushed this as a branch on this repo, `testbed-interventions`, please feel free to push your commit doing the blacklisting into the branch whenever you have time to do so. :)
> Add testbed interventions for manual verification.

- src/data/injections.js
- src/injections/css/bug1568908-console.cloud.google.com-scrollbar-fix.css
This is the fix for https://github.com/webcompat/web-bugs/issues/33164.
r? @ksy36
> Bug 1568908 - Remove duplicate scrollbar in Google Cloud Console.

- src/injections/css/bug1561371-mail.google.com-allow-horizontal-scrolling.css
See https://bugzilla.mozilla.org/show_bug.cgi?id=1581967
Fixes https://github.com/webcompat/web-bugs/issues/40308
Fixes https://github.com/webcompat/web-bugs/issues/40312
Fixes https://github.com/webcompat/web-bugs/issues/40151
Fixes https://github.com/webcompat/web-bugs/issues/37687
Fixes https://github.com/webcompat/web-bugs/issues/40236
> Bug 1581967 - Modify Gmail intervention to not break menus

- src/data/ua_overrides.js
- src/experiment-apis/sharedPreferences.js
- src/experiment-apis/sharedPreferences.json
- src/lib/injections.js
- src/lib/ua_overrides.js
- src/manifest.json
This adds a control experiment branch for the enhanced search feature, as well as having it emit the addon version to fennec telemetry, and only send extra telemetry when a user is in the experiment (or triggers the testing pref).
Note there is also a minor change injections.js to keep mach lint from complaining.
Also note that any necessary companion changes to the Fennec java files will be made in a separate patch on bug 1585380.
> Bug 1585380 - Add support for a control experiment branch

- .circleci/config.yml
- .githooks/pre-push
- Jakefile
- README.md
- package.json
- src/data/injections.js
- src/injections/css/bug1605611-maps.google.com-directions-time.css
- src/injections/js/bug1605611-maps.google.com-directions-time.js
This PR does a couple of things.
* Downgrades `prettier` to the [version in use inside `mozilla-central`](https://searchfox.org/mozilla-central/rev/be7d1f2d52dd9474ca2df145190a817614c924e4/package.json#24), because different `prettier` versions do different things occasionally...
* Updates dev dependencies - mainly to remove an annoying security warning.
* Changes the CircleCI configs so that stylecheck failures will now turn a PR red.
* Fixes existing codestyle violations, as the PR would fail otherwise.
* Supplies a `pre-push` hook that runs jasmine tests and codestyle verifications, as well as adds documentation on how to use the hook. I wanted to use a `pre-commit` hook first, but since the whole process takes a bit of time, I decided against that.
* Changes the `jake` exporter so …
> Run codestyle checks on CI, and other goodies.

- src/data/ua_overrides.js
This removes unused interventions as investigated by Oana in https://github.com/mozilla/webcompat-team-okrs/issues/121#issuecomment-579171677.
r? @ksy36
> Intervention cleanup

- src/data/ua_overrides.js
This is for [bug 1442050](https://bugzilla.mozilla.org/show_bug.cgi?id=1442050). Simply appending the identifier to our UA works fine.
r? @ksy36
> Bug 1442050 - Add `AppleWebKit` identifer to UA on my.nintendo.com.

- src/data/ua_overrides.js
In [bug 1525839](https://bugzilla.mozilla.org/show_bug.cgi?id=1525839), Karl identified some additional Baidu domains that need overwriting.
r? @ksy36
> Bug 1525839 - Add more domains to the Baidu UA override.

- src/data/injections.js
- src/injections/css/bug1610344-directv.com.co-hide-unsupported-message.css
See also [bug 1610344](https://bugzilla.mozilla.org/show_bug.cgi?id=1610344).
r? @ksy36
> Bug 1610344 - Hide "Browser is not supported" message on directv.com.co.

- Jakefile
With more people working on and with the addon now, let's make the process as smooth as possible and reduce the amount of accidental oversights one run into. :)
r? @ksy36 
Closes #100
> Bug #100 - Skip moz.build when exporting into Android Components.

- package.json
- src/lib/injections.js
This is a preparation so we're ready whenever the changes happen on `mozilla-central`. Do not merge this PR before [bug 1620218](https://bugzilla.mozilla.org/show_bug.cgi?id=1620218) is landed.
> Bug 1620218 - Upgrade Prettier to 1.18.2.

- README.md
Current documentation is outdated, since it still publicly recommends `web-ext`, which unfortunately is no longer a solution for most people. Also, there was no guidance of how to test things inside Fenix/AC, so I added that as well.
r? @ksy36 
closes #54
> Bug #54 - Update documentation to reflect the new landscape of mobile testing.

- src/data/ua_overrides.js
Follow-up, as this catches more cases. See Softvisions comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1525839#c4
r? @miketaylr
> Bug 1525839 - Override full User Agent for Baidu sites.

- src/data/ua_overrides.js
As per the discussion [on Phab]https://phabricator.services.mozilla.com/D59064), this only removes the intervention. We're using everything else in other places (the Google Maps injection, to be precise), so there is no need to remove that.
r? @miketaylr
> Bug 1607525 - Remove Enhanced Search Experiment intervention.

- src/data/ua_overrides.js
If we don't have "Chrome" in the UA string, we're detected as
an older version of Android and our users get a scary modal.
I've tested locally on Fennec and the Sample browser from AC.
r? @ksy36
> Bug 1621065 - Write UA override for bracketchallenge.ncaa.com

- package.json
- src/about-compat/AboutCompat.jsm
This will stay a draft PR until [this Phabricator revisoin](https://phabricator.services.mozilla.com/D66128) is landed. It's likely this will need a quick rebase with the upcoming changes to this addon, but it shouldn't be too bad (the second commit is automated via `npm run prettier` anyway. :))
> Bug 1620556 - Upgrade Prettier to 1.19.x

- src/data/ua_overrides.js
I've verified this fixes the bug as reported -- comments can be viewed, and toggled.
(The version isn't used at all, but if it's not there the page throws and breaks)
> Bug 1622059 - Add UA override for sites using img.weblogssl.com script

- src/data/ua_overrides.js
I've tested this works locally, at least for the log-in page.
> Bug 1622081 - Add UA override for m2.bmo.com

- package.json
- spec/support/jasmine.json
- src/about-compat/aboutPage.json
- src/experiment-apis/aboutConfigPrefs.json
mozilla-central is not (yet?) doing that, but since prettier can work on .json files and is doing a fairly good job of keeping them readable, let's remove one additional point of ambiguity and have our embedded prettier do the job for us.
r? @miketaylr
> Also run prettier on .json files

- src/data/picture_in_picture_overrides.js
OK, so Netflix has a lot of domains. I've tested all of these (via curl and commandline fetch hax), cobbled from a few sources. I'm slightly concerned that we're increasing memory usage by adding 200 new PiP policy overrides for all our users, when they likely only need this for a single Netflix TLD.
r? @denschub 
Also cc @adamopenweb, just to see if he thinks we should trim the list of Netflix domains.
> Bug 1546051 - Hide PiP on Netflix previews

- src/data/injections.js
- src/injections/js/bug1641998-embedded-twitter-videos-etp-indexeddb.js
Follow-up to yesterday, as I didn't get required information in time.
r? @ksy36
> Bug 1641998 - Overwride IndexedDB APIs for embedded Twitter videos.

- src/data/injections.js
This will fix the issue with the donotshowunsupported message cloudreadykb.neverware.com.
> Bug 1649325. Adds cloudreadykb.neverware.com to salesforce issue

- src/data/picture_in_picture_overrides.js
(See https://bugzilla.mozilla.org/show_bug.cgi?id=1655665#c7 for context).
> Hide picture-in-picture toggle on NetFlix /latest landings. Fixes #171

- Jakefile
- README.md
- spec/available_injections.spec.js
- spec/available_ua_overrides.spec.js
- spec/helpers/webext_manifest_schema.js
- src/injections/js/bug1452707-window.controllers-shim-ib.absa.co.za.js
- src/injections/js/bug1457335-histography.io-ua-change.js
- src/injections/js/bug1472075-bankofamerica.com-ua-change.js
- src/injections/js/bug1570856-medium.com-menu-isTier1.js
- src/injections/js/bug1579159-m.tailieu.vn-pdfjs-worker-disable.js
- src/injections/js/bug1610358-pcloud.com-appVersion-change.js
- src/injections/js/bug1654906-contentDocument-fix.js
- src/lib/console_warning_helper.js
- src/lib/custom_functions.js
- src/lib/injections.js
- src/lib/ua_overrides.js
- src/manifest.json
- src/moz.build
This PR collects a couple of "someone needs to do it"-patches I built in the last couple of weeks, but I wanted to collect them and land in between rotations, so I don't mess up someone's work. :) Reviewing by commit instead of looking at the whole patch is highly recommended.
There are seven commits in total, in the order they appear on GitHub:
1. Removes a bit of leftover from #178, where parts of the build tooling weren't removed with the Fennec documentation.
2. Creates a bit of documentation in the README on how to run the in-tree tests.
3. Adds validation rules for the URLs used in match patterns to avoid future breakage caused by invalid patterns.
4. That's a refactoring of Tom's old PR, #64. It's still doing the same, but I altered the message to be a bit more friendly. :)
5. …
> Collection of various "maintenance" patches.

- src/lib/ua_overrides.js
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1653296, this is probably the easiest way. The UA will get manipulated for the Desktop Mode anyway, so there isn't really a point to us doing overrides.
I honestly don't know how to test this, since our unit tests do not actually fire the handler. The change can be verified using the testbed, but that's not ideal. We probably should move more tests into the browser runtime at some point. :/
r? @ksy36
> Bug 1653296 - Don't override the UA on mobile if Request Desktop Site is enabled.

- src/data/injections.js
- src/injections/css/bug1666771-zilow-map-overdraw.css
This addresses the performance issues caused by overdraw as reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1662297.
r? @ksy36
> Bug 1666771 - Create CSS intervention for zillow.com.

- src/data/ua_overrides.js
This addresses the issues described in https://bugzilla.mozilla.org/show_bug.cgi?id=1665720. I have reached out to them, but have not yet heard back, so this is worth overriding.
r? @ksy36
> Bug 1666754 - Add mobile UA override for lffl.org.

- src/injections/js/bug1682238-gamearter.com-ua-change.js
11.1 was released today, so let's update that intervention...
r? @ksy36
> Bug 1682238 - Replace all macOS 11.x User Agent strings, not just 11.0.

- src/experiment-apis/appConstants.js
- src/lib/shims.js
Rob Wu discovered this one in https://bugzilla.mozilla.org/show_bug.cgi?id=1712959 - AppConstants.BETA_OR_RELEASE doesn't actually exist. 
> Bug 1712959 - use AppConstants.RELEASE_OR_BETA instead of AppConstants.BETA_OR_RELEASE.

- package-lock.json
- package.json
- src/data/injections.js
- src/data/ua_overrides.js
- src/injections/css/bug1719870-lcbo.com-table-clearfix.css
The usual fun, all in one PR, including a commit that updates the build deps to include security fixes.
This patch set does not include a version number bump - as usual, I bump the version number while landing in m-c and a-c, and only push the bump-commit to this repo once it's landed. This gives me the chance to publish eventual follow-up/fix-commits without having a messy history or burning a dot-release. :)
> Bug 1714611 - Ship v24.0.0 of webcompat system addon

- .taskcluster.yml
- package.json
- taskcluster/ci/build/kind.yml
- taskcluster/ci/test/kind.yml
- taskcluster/xpi_taskgraph/build.py
- taskcluster/xpi_taskgraph/signing.py
- taskcluster/xpi_taskgraph/test.py
- taskcluster/xpi_taskgraph/xpi_manifest.py
(Hopefully) fixes #230.
Opening a PR to see if CI runs again.
> Use `node-lts-latest` Docker image in CI.

- spec/available_shims.spec.js
- spec/helpers/webext_manifest_schema.js
This is not meant to replace the in-product test or our work-in-progress test suite. but it provides a first stage of defense against common errors. The tests added here catch:
- Syntax errors in the definition file
- Missing or non-unique shim IDs
- Missing or invalid platform targets
- Missing bug IDs
- Missing or invalid URL match patterns
---
@wisniewskit and I briefly chatted about this before, but Tom didn't find the time so far, and I needed a bit of productivity right now. :)
> No bug - Add bare-minimum specs for Shims.

- src/manifest.json
Version bump to 30.0.0 after [1749436](https://bugzilla.mozilla.org/show_bug.cgi?id=1749436) landed.
> Bug 1749436 - Bump version number to 30.0.0

- Jakefile
- README.md
- package-lock.json
- package.json
To us, the version number in `package.json` is pretty useless. We used to keep this manually in sync with the `manifest.json`s setting, but in https://github.com/mozilla-extensions/webcompat-addon/commit/7a445d242a8354c1b9347a60d415932091f753dc, I decided to stop that and just have it say `1.0.0` all the time, because to us, the relevant information is in `manifest.json` only.
Unfortunately, this causes an issue. CI uses the `package.json`s version number to set the version number in .xpi, and thus this is also relevant during rollouts. I discovered this during the recent Release-Hotfix, where the rollout systems wanted to deploy a version `1.0.0`. I talked to the Addons Pipeline team, and while they agreed that this is not perfect, reading the version from `manifest.json` isn't really an …
> Issue #256 - Add tooling to ensure and assist with the package.json version number

- src/manifest.json
This adds a new permission, `mozillaAddons`. As per the email sent from TheOne three hours ago, this will be required for ShipIt starting around May 30.
I'm basing this PR on `release-hotfix` as there is a non-zero chance we have to ship an update before this change reaches the right tree. There is no need to land this in central, we can just merge this whenever the next update rolls around.
r? @ksy36, but please don't merge (I'll merge this into release-hotfix and main at the same time)
> No bug - Add the mozillaAddons permission.

- src/data/ua_overrides.js
- src/lib/ua_helpers.js
I've retested all overrides that are using `getDeviceAppropriateChromeUA` and all work as expected with newer version, here is the list:
site | device
-- | --
wp1-ext.usps.gov | - android
autotrader.ca | - android
lffl.org | - android
app.xiaomi.com | - android
www.dealnews.com | - android
apppmedia.jp | - android
covid.cdc.gov | - both
vmos.cn | - android
yebocasino.co.za | - android
automesseweb.jp | - android
slrclub.com | - android
workflow.base.vn | - android
nordjyske.dk | - android
www.dolcegabbana.com | - android
www.otsuka.co.jp | - desktop
animalplanet.com | - android
frontgate.com | - android
It would be nice to update version for interventions that don't use `getDeviceAppropriateChromeUA` function and have hardcoded UA strings. I've filed a separate issue for that …
> Fixes #249 - Update the default Chrome version for UA overrides in getDeviceAppropriateChromeUA

- src/injections/css/bug1784199-entrata-platform-unsupported.css
I've noticed the site also returns the following rule in the html template (together with the unsupported message html and the rest of css):
```css
* {
color: #000000;
}
```
That affects menu items on one of the sites and cookie popup font color on all sites. So in this PR I unset the color.
Before and after below:
> Bug 1784199 - Font color reset for cookie popup and menu items

- Jakefile
- README.md
This adjusts the export tooling to be able to export into the new [firefox-android monorepo](https://github.com/mozilla-mobile/firefox-android), since the old android-components repo is now archived.
While the jake export job is still called `export-ac`, I renamed the environment variable used to indicate the path of the repo. What used to be called `EXPORT_AC_LOCATION` is now called `EXPORT_ANDROID_MONOREPO_LOCATION`, and it should point to the **root directory** of your local `firefox-android` clone!
If you have set this variable in your `.zshrc` or `.bashrc` or whereever, **now** is a good chance to adjust that!
Explicitly pinging both @ksy36 and @wisniewskit for visibility. Note that the old workflow will no longer work, so you have to adjust your ENV vars before you touch the addon …
> Adjust export tooling for the new firefox-android monorepo.

- src/manifest.json
Also bump the min version to the current ESR 102. We don't really test the experiment APIs in older releases anyway.
This appears to be working fine, including installing an .xpi over an existing installation. I see no downside to this, so let's ship it.
> Bug 1799369 - Use `browser_specific_settings` instead of `applications` in the manifest.

- src/lib/ua_helpers.js
The Android version in the UA string has the format `Android 42`, not `Android/42`. This most likely was a copy-paste bug.
r? @wisniewskit, please merge before your interventions to make sure this is included in 108.
> Bug 1794970 - Fix Android version RegEx.

- src/data/ua_overrides.js
it is another domain of gbf. mabe this compat workaround also works for it. but i haven't tested yet. because i have only a phone at this moment
see also: https://github.com/webcompat/web-bugs/issues/34310#issuecomment-1708967412
> apply ua override for gbf.game.mbga.jp

- package-lock.json
- package.json
- spec/helpers/mock_webextension_apis.js
- spec/injections.spec.js
- src/data/shims.js
- src/lib/injections.js
- src/lib/shims.js
- src/manifest.json
This PR include a draft of the changes needed to port the webcompat interventions builtin addon from the contentScripts.register API method to the scripting.registerContentScripts API method.
The motivation behind it is that the content scripts dynamically registered using contentScripts.register are expected to be unregistered automatically if the background page is destroyed, while the ones registered through the scripting.registerContentScripts API are expected to stay registered even after the background page is destroyed.
While this PR does not aim to convert the persistent background page into an event page, it may still be interesting to consider it on its own, because it would still help to make the webcompat interventions to be more resilient to extension process …
> Porting webcompat interventions injections from contentScripts to scripting API

- src/about-compat/AboutCompat.sys.mjs
- src/about-compat/aboutPage.js
- src/about-compat/aboutPageProcessScript.js
- src/components.conf
- src/moz.build
This converts AboutCompat.jsm to an ES module and changes the necessary support infrastructure.
I have not tested it on android, so I'm not certain it will work there. Performing the export on desktop and running the tests seems to work fine.
> Fixes #275: Convert AboutCompat.jsm to an ES module.

- Jakefile
- README.md
This also adds a new command, `npm run jake export`, that will export both mobile and desktop. Since those two are in the same repository anyway, I don't see a good reason to separate them in most use-cases. The individual commands still exist, though, in case you only need to update one.
r? @ksy36 
fyi! @wisniewskit
> No bug - Adjust export tooling for the in-tree Android Components.

- spec/all_interventions.spec.js
- spec/available_injections.spec.js
- spec/available_shims.spec.js
- spec/available_ua_overrides.spec.js
- src/data/injections.js
- src/data/ua_overrides.js
Previously, the tests only verified that the ID is unique within each "kind" of intervention (i.e. UA override, Injection, Shim). This isn't reliable in practice.
The "disable" button on `about:compat` sends a message with `{ command: "toggle", id }` to the broker, and it doesn't distinguish between the different kinds of interventions. So the ID has to be globally unique, not just within each set.
This fixes the one instance where this happened, and also moves the test for this into a global test.
Fixes #333.
> Issue #333 - Ensure all interventions have a globally unique ID.

- src/data/injections.js
This adds `x.com` to the Twitter DraftJS intervention. I decided not to remove the old domains, just in case they decide to switch back again...
r? @ksy36
> Bug 1776229 - Add x.com to the Twitter DraftJS intervention.

- package-lock.json
- package.json
- src/data/injections.js
- src/manifest.json
We also need to match the base YouTube Shorts domain, otherwise pull-to-refresh will still work once on the tab if the user directly visits m.youtube.com/shorts
> Bug 1904556 - fix the CSS intervention to disable pull-to-refresh on the YouTube Shorts mobile page

- package-lock.json
- package.json
- src/data/injections.js
- src/injections/js/bug1815733-outlook365-clipboard-read-noop.js
- src/manifest.json
r? @wisniewskit 
See https://bugzilla.mozilla.org/show_bug.cgi?id=1815733#c13 for why. this seems to work, and pasting still works, but without the annoying native popover.
> Bug 1815733 - Override navigator.clipboard.read() with a no-op for Outlook.

- Jakefile
To test, you can
- `npm install`
- `npm run jake build`
after which you'll find the processed sources inside the `build/` directory, where the `run.js` file should have been preprocessed accordingly.
> Add Jake task to inject new JSON payload into `run.js`.
